### ISSUE TITLE
Extend interface selector

### ISSUE THREAD

**Issue by unfokus** [wobcom/Cisco-Exporter#8]
It's already possible to specify interfaces that should be scraped. This is required for routers that have a huge number of virtual interfaces, like BNGs.

```yaml
devices:
  hostname.example.com:
    interfaces:
      - HundredGigE0/0/0
      - GigabitEthernet0
```

We should extend the feature to allow the use of regexes in the interface list.
Additionally we should allow to _exclude_ specific interfaces based on a list of regexes.

The config interface would look like this:

```yaml
devices:
  hostname.example.com:
    interfaces:
      - HundredGig.*
  hostname2.example.com:
    interfaces_excluded: 
      - Virtual-Template.*
```

To implement this we first need to fetch the list of all interfaces (`show interface summary`), filter based on our selectors and then fetch the individual interfaces.

When both `interfaces` and `interfaces_excluded` are empty we should continue to use the simple implementation where `show interfaces` is collected without further arguments, for performance reasons.
